<header>
    <nav>
      <div>
        <ul class="menu">
          <li class="menu" id="logo"><img src="images/logo.png" alt="logo" height="50" width="150" /></li>
          <li class="menu"><a <?php echo($page=="index_page")?"class='active'":""; ?> href="index.php"><i id="hm" class="fa fa-fw fa-home"></i>Home</a></li>
          <li class="menu"><a <?php echo($page=="product_page")?"class='active'":""; ?> href="product.php"><i id="conv" class="material-icons">add_location</i>Venues</a></li>
          <li class="menu"><a <?php echo($page=="enquire_page")?"class='active'":""; ?> href="enquire.php"><i id="prsn" class="fa fa-fw fa-user"></i>Enquire</a></li>
          <li class="menu"><a <?php echo($page=="payment_page")?"class='active'":""; ?> href="payment.php">&#36; Payment</a></li>
          <li class="menu"><a <?php echo($page=="about_page")?"class='active'":""; ?> href="about.php"><i id="abt" class="material-icons">info</i>  About</a></li>
          <li class="menu"><a <?php echo($page=="enhancements_page")?"class='active'":""; ?> href="enhancements.php"><i id="more" class="material-icons">more</i>  En1</a></li>
          <li class="menu"><a <?php echo($page=="enhancements2_page")?"class='active'":""; ?> href="enhancements2.php"><i id="more1" class="material-icons">more</i>  En 2</a></li>
          <li class="menu"><a <?php echo($page=="manager_page")?"class='active'":""; ?> href="manager.php"><i id="prsn" class="fa fa-fw fa-user"></i>Manager</a></li>
          <li class="menu"><a <?php echo($page=="enhancements3_page")?"class='active'":""; ?> href="enhancements3.php"><i id="more1" class="material-icons">more</i>En3</a></li>
          <li class="menu" id="social"><img src="images/social.jpg" alt="social" height="50" width="200" /></li>
        </ul>
      </div>
    </nav>
</header>
